name: Test

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [39, 310, 311, 312, 313]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install maturin pytest

      - name: Build and install package
        run: |
          maturin develop --release

      - name: Run tests
        run: |
          python tests/test_word_tokenize.py

      - name: Test import
        run: |
          python -c "import parrotnlp; print('✅ parrotnlp imports successfully')"
          python -c "from parrotnlp import word_tokenize, VietnameseWordSegmenter; print('✅ All functions available')"

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install maturin

      - name: Check Rust code
        run: |
          cargo check
          cargo clippy -- -D warnings

      - name: Check Python package structure
        run: |
          python -c "import parrotnlp; print('Package structure is valid')"
